config/routes.rb
Rails.application.routes.draw do
 
  resources :logs
  resources :salaries
  resources :employees
  resources :tax_brackets
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Gaji', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Employees", employees_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Tax Brackets", tax_brackets_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Salaries", salaries_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Logs", logs_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", home_about_path, class:"nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About ..</h1>

app/views/home/index.html.erb
<h1>Hello World!</h1>
My first page in Ruby on Rails 