config/routes.rb
Rails.application.routes.draw do
 
  resources :logs
  resources :salaries
  resources :employees
  resources :tax_brackets
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/salary.rb
class Salary < ApplicationRecord
  belongs_to :employees
  has_one :tax_brackets

  
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :set_salary, only: %i[ show edit update destroy ]

  # GET /salaries or /salaries.json
  def index
    @salaries = Salary.all
  end

  # GET /salaries/1 or /salaries/1.json
  def show
  end

  # GET /salaries/new
  def new
    @salary = Salary.new
    @employee = Employee.all

    # if (@salary.salary > 1000) 
    #   tax_bracket_id = 4
    # end
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries or /salaries.json
  def create
    @salary = Salary.new(salary_params)

    if (@salary.salary > 180001)
      @salary.tax_bracket_id = 1
    elsif (@salary.salary > 80001)
      @salary.tax_bracket_id = 2
    elsif (@salary.salary > 40001)
      @salary.tax_bracket_id = 3
    elsif (@salary.salary > 20001)
      @salary.tax_bracket_id = 4
    elsif (@salary.salary > 1)
      @salary.tax_bracket_id = 5
    end 

    @salary.annual_salary = @salary.salary * 12
    
    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: "Salary was successfully created." }
        format.json { render :show, status: :created, location: @salary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1 or /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to @salary, notice: "Salary was successfully updated." }
        format.json { render :show, status: :ok, location: @salary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1 or /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url, notice: "Salary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def salary_params
      params.require(:salary).permit(:salary, :annual_salary, :monthly_nett_income, :employee_id)
      # params.require(:employee).permit(employee_id: [])
      
    end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/_form.html.erb
<%= form_with(model: salary) do |form| %>
  <% if salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
        <% salary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee %>
    <%= select_tag("employee_id", options_from_collection_for_select(@employee, 'id', 'name')) %>
    
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<h1>Editing Salary</h1>

<%= render 'form', salary: @salary %>

<%= link_to 'Show', @salary %> |
<%= link_to 'Back', salaries_path %>
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/salaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salaries</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Salary</th>
      <th>Annual salary</th>
      <th>Monthly nett income</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.salary %></td>
        <td><%= salary.annual_salary %></td>
        <td><%= salary.monthly_nett_income %></td>
        <td><%= link_to 'Show', salary %></td>
        <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salary', new_salary_path, class:"btn btn-primary" %>

app/views/salaries/new.html.erb
<h1>New Salary</h1>

<%= render 'form', salary: @salary %>

<%= link_to 'Back', salaries_path %>

app/views/salaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salary:</strong>
  <%= @salary.salary %>
</p>

<p>
  <strong>Annual salary:</strong>
  <%= @salary.annual_salary %>
</p>

<p>
  <strong>Monthly nett income:</strong>
  <%= @salary.monthly_nett_income %>
</p>

<p>
  <strong>Tax rate:</strong>
  <%= @salary.tax_bracket_id %>
</p>

<p>
  <strong>Employee:</strong>
  <% @salary.employees.each do |employee| %>
    <%= employee.id %>
    <% end %>
</p>

<%= link_to 'Edit', edit_salary_path(@salary) %> |
<%= link_to 'Back', salaries_path %>