config/routes.rb
Rails.application.routes.draw do
 
  resources :logs
  resources :salaries
  resources :employees
  resources :tax_brackets
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :employees
     
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: %i[ show edit update destroy ]

  # GET /logs or /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1 or /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs or /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: "Log was successfully created." }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1 or /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: "Log was successfully updated." }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1 or /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: "Log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def log_params
      params.require(:log).permit(:timestamp, :annual_salary, :monthly_income_tax)
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :timestamp %>
    <%= form.datetime_select :timestamp %>
  </div>

  <div class="field">
    <%= form.label :annual_salary %>
    <%= form.text_field :annual_salary %>
  </div>

  <div class="field">
    <%= form.label :monthly_income_tax %>
    <%= form.text_field :monthly_income_tax %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Timestamp</th>
      <th>Annual salary</th>
      <th>Monthly income tax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.timestamp %></td>
        <td><%= log.annual_salary %></td>
        <td><%= log.monthly_income_tax %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path, class:"btn btn-primary" %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Timestamp:</strong>
  <%= @log.timestamp %>
</p>

<p>
  <strong>Annual salary:</strong>
  <%= @log.annual_salary %>
</p>

<p>
  <strong>Monthly income tax:</strong>
  <%= @log.monthly_income_tax %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>